
CC=g++
FLAGS=-Wall -std=c++14 -Werror -pedantic-errors
OBJS=q1.cpp

all
	${CC} ${FLAGS} ${OBJS} -o q1


old
	${CC} ${FLAGS} q1.o -o q1


clean
	echo Cleaning
	rm -f q1.o
	${CC} ${FLAGS} ${OBJS} -o q1

